-- Migration 0015: Deep Character Attributes + Expanded Scene Parameters
-- Adds full character profile fields and director-grade scene controls

-- ─── Characters: add deep profile columns ───
ALTER TABLE `characters` ADD `nationality` varchar(128);--> statement-breakpoint
ALTER TABLE `characters` ADD `countryOfOrigin` varchar(128);--> statement-breakpoint
ALTER TABLE `characters` ADD `cityOfOrigin` varchar(128);--> statement-breakpoint
ALTER TABLE `characters` ADD `dateOfBirth` varchar(64);--> statement-breakpoint
ALTER TABLE `characters` ADD `zodiacSign` varchar(32);--> statement-breakpoint
ALTER TABLE `characters` ADD `occupation` varchar(255);--> statement-breakpoint
ALTER TABLE `characters` ADD `educationLevel` varchar(128);--> statement-breakpoint
ALTER TABLE `characters` ADD `socialClass` varchar(64);--> statement-breakpoint
ALTER TABLE `characters` ADD `religion` varchar(128);--> statement-breakpoint
ALTER TABLE `characters` ADD `languages` json;--> statement-breakpoint
ALTER TABLE `characters` ADD `personality` json;--> statement-breakpoint
ALTER TABLE `characters` ADD `backstory` text;--> statement-breakpoint
ALTER TABLE `characters` ADD `motivations` text;--> statement-breakpoint
ALTER TABLE `characters` ADD `fears` text;--> statement-breakpoint
ALTER TABLE `characters` ADD `secrets` text;--> statement-breakpoint
ALTER TABLE `characters` ADD `strengths` json;--> statement-breakpoint
ALTER TABLE `characters` ADD `weaknesses` json;--> statement-breakpoint
ALTER TABLE `characters` ADD `speechPattern` varchar(255);--> statement-breakpoint
ALTER TABLE `characters` ADD `accent` varchar(128);--> statement-breakpoint
ALTER TABLE `characters` ADD `catchphrase` varchar(512);--> statement-breakpoint
ALTER TABLE `characters` ADD `relationships` json;--> statement-breakpoint
ALTER TABLE `characters` ADD `environmentPreference` varchar(255);--> statement-breakpoint
ALTER TABLE `characters` ADD `preferredWeather` varchar(128);--> statement-breakpoint
ALTER TABLE `characters` ADD `preferredSeason` varchar(64);--> statement-breakpoint
ALTER TABLE `characters` ADD `preferredTimeOfDay` varchar(64);--> statement-breakpoint
ALTER TABLE `characters` ADD `arcType` varchar(128);--> statement-breakpoint
ALTER TABLE `characters` ADD `moralAlignment` varchar(64);--> statement-breakpoint
ALTER TABLE `characters` ADD `emotionalRange` json;--> statement-breakpoint
ALTER TABLE `characters` ADD `physicalAbilities` json;--> statement-breakpoint
ALTER TABLE `characters` ADD `mentalAbilities` json;--> statement-breakpoint
ALTER TABLE `characters` ADD `specialSkills` json;--> statement-breakpoint
ALTER TABLE `characters` ADD `wardrobe` json;--> statement-breakpoint
ALTER TABLE `characters` ADD `voiceType` varchar(128);--> statement-breakpoint
ALTER TABLE `characters` ADD `voiceId` varchar(255);--> statement-breakpoint
ALTER TABLE `characters` ADD `role` varchar(128);--> statement-breakpoint
ALTER TABLE `characters` ADD `storyImportance` varchar(64);--> statement-breakpoint
ALTER TABLE `characters` ADD `screenTime` varchar(64);--> statement-breakpoint

-- ─── Scenes: add director-grade parameters ───
ALTER TABLE `scenes` ADD `videoUrl` text;--> statement-breakpoint
ALTER TABLE `scenes` ADD `videoJobId` varchar(255);--> statement-breakpoint
ALTER TABLE `scenes` ADD `lensType` varchar(128);--> statement-breakpoint
ALTER TABLE `scenes` ADD `focalLength` varchar(64);--> statement-breakpoint
ALTER TABLE `scenes` ADD `depthOfField` varchar(64);--> statement-breakpoint
ALTER TABLE `scenes` ADD `cameraMovement` varchar(128);--> statement-breakpoint
ALTER TABLE `scenes` ADD `shotType` varchar(64);--> statement-breakpoint
ALTER TABLE `scenes` ADD `frameRate` varchar(32);--> statement-breakpoint
ALTER TABLE `scenes` ADD `aspectRatio` varchar(16);--> statement-breakpoint
ALTER TABLE `scenes` ADD `colorPalette` varchar(255);--> statement-breakpoint
ALTER TABLE `scenes` ADD `colorTemperature` varchar(64);--> statement-breakpoint
ALTER TABLE `scenes` ADD `season` varchar(32);--> statement-breakpoint
ALTER TABLE `scenes` ADD `country` varchar(128);--> statement-breakpoint
ALTER TABLE `scenes` ADD `city` varchar(128);--> statement-breakpoint
ALTER TABLE `scenes` ADD `locationDetail` text;--> statement-breakpoint
ALTER TABLE `scenes` ADD `foregroundElements` text;--> statement-breakpoint
ALTER TABLE `scenes` ADD `backgroundElements` text;--> statement-breakpoint
ALTER TABLE `scenes` ADD `characterBlocking` text;--> statement-breakpoint
ALTER TABLE `scenes` ADD `emotionalBeat` varchar(255);--> statement-breakpoint
ALTER TABLE `scenes` ADD `actionDescription` text;--> statement-breakpoint
ALTER TABLE `scenes` ADD `vfxNotes` text;--> statement-breakpoint
ALTER TABLE `scenes` ADD `sfxNotes` text;--> statement-breakpoint
ALTER TABLE `scenes` ADD `ambientSound` varchar(255);--> statement-breakpoint
ALTER TABLE `scenes` ADD `musicMood` varchar(128);--> statement-breakpoint
ALTER TABLE `scenes` ADD `musicTempo` varchar(64);--> statement-breakpoint
ALTER TABLE `scenes` ADD `dialogueLines` json;--> statement-breakpoint
ALTER TABLE `scenes` ADD `subtitleText` text;--> statement-breakpoint
ALTER TABLE `scenes` ADD `visualEffects` json;--> statement-breakpoint
ALTER TABLE `scenes` ADD `props` json;--> statement-breakpoint
ALTER TABLE `scenes` ADD `wardrobe` json;--> statement-breakpoint
ALTER TABLE `scenes` ADD `makeupNotes` text;--> statement-breakpoint
ALTER TABLE `scenes` ADD `stuntNotes` text;--> statement-breakpoint
ALTER TABLE `scenes` ADD `budgetEstimate` int;--> statement-breakpoint
ALTER TABLE `scenes` ADD `shootingDays` float;--> statement-breakpoint
ALTER TABLE `scenes` ADD `aiPromptOverride` text;--> statement-breakpoint
