CREATE TABLE `directorVision` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`userId` int NOT NULL,
	`cameraSystem` varchar(128),
	`lensSet` varchar(128),
	`aspectRatio` varchar(16),
	`frameRate` varchar(16),
	`shootingFormat` varchar(64),
	`colorGradeStyle` varchar(128),
	`referenceFilms` json,
	`colorPalette` json,
	`lutName` varchar(128),
	`movementStyle` varchar(128),
	`coverageNotes` text,
	`lightingStyle` varchar(128),
	`soundDesignDirection` text,
	`musicGenre` varchar(128),
	`productionEra` varchar(128),
	`productionCountry` varchar(128),
	`productionSetting` text,
	`architecturalStyle` varchar(128),
	`visualDnaPrompt` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `directorVision_id` PRIMARY KEY(`id`),
	CONSTRAINT `directorVision_projectId_unique` UNIQUE(`projectId`)
);
--> statement-breakpoint
CREATE TABLE `growth_assets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaign_id` int,
	`segment` varchar(64) NOT NULL,
	`platform` varchar(64) NOT NULL,
	`asset_type` varchar(64) NOT NULL,
	`title` varchar(255),
	`headline` varchar(512),
	`body` text NOT NULL,
	`visual_prompt` text,
	`media_url` text,
	`utm_url` text,
	`status` varchar(32) NOT NULL DEFAULT 'draft',
	`rejection_note` text,
	`published_at` timestamp,
	`published_url` text,
	`quality_score` int NOT NULL DEFAULT 0,
	`impressions` int NOT NULL DEFAULT 0,
	`clicks` int NOT NULL DEFAULT 0,
	`conversions` int NOT NULL DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `growth_assets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `growth_audiences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`segment` varchar(64) NOT NULL,
	`name` varchar(255),
	`organisation` varchar(255),
	`website` varchar(500),
	`public_profile_url` varchar(500),
	`country` varchar(128),
	`email` varchar(255),
	`source` varchar(128) NOT NULL DEFAULT 'manual',
	`utm_source` varchar(128),
	`utm_medium` varchar(128),
	`utm_campaign` varchar(128),
	`score` int NOT NULL DEFAULT 0,
	`tags` json,
	`notes` text,
	`status` varchar(32) NOT NULL DEFAULT 'discovered',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `growth_audiences_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `growth_campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`segment` varchar(64) NOT NULL,
	`offer` varchar(500),
	`cta` varchar(255),
	`objective` varchar(255) NOT NULL DEFAULT 'awareness',
	`channels` json,
	`status` varchar(32) NOT NULL DEFAULT 'draft',
	`ad_spend` int NOT NULL DEFAULT 0,
	`pack_ideas` json,
	`start_date` timestamp,
	`end_date` timestamp,
	`metrics` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `growth_campaigns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `growth_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event_type` varchar(64) NOT NULL,
	`source` varchar(128),
	`utm_medium` varchar(128),
	`utm_campaign` varchar(128),
	`utm_content` varchar(128),
	`utm_term` varchar(128),
	`segment` varchar(64),
	`page` varchar(255),
	`referrer` text,
	`user_id` int,
	`audience_id` int,
	`asset_id` int,
	`campaign_id` int,
	`metadata` json,
	`ip` varchar(45),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `growth_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `productionVehicles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`make` varchar(128),
	`model` varchar(128),
	`year` int,
	`color` varchar(128),
	`condition` varchar(64),
	`vehicleRole` varchar(64) DEFAULT 'hero',
	`vehicleType` varchar(64),
	`period` varchar(64),
	`specialFeatures` text,
	`sceneIds` json,
	`aiVisualPrompt` text,
	`referenceImages` json,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `productionVehicles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shootingDays` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`userId` int NOT NULL,
	`dayNumber` int NOT NULL,
	`locationName` varchar(255),
	`scenes` json,
	`callTime` varchar(16),
	`wrapTime` varchar(16),
	`estimatedPages` varchar(32),
	`notes` text,
	`lightingWindow` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shootingDays_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `shotListItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`userId` int NOT NULL,
	`sceneName` varchar(255) NOT NULL,
	`sceneNumber` varchar(32),
	`shotNumber` varchar(16) NOT NULL,
	`shotType` varchar(32),
	`lensLength` varchar(32),
	`cameraMovement` varchar(64),
	`frameDescription` text,
	`action` text,
	`dialogue` text,
	`estimatedDuration` float,
	`lightingNote` text,
	`directorNote` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shotListItems_id` PRIMARY KEY(`id`)
);
