CREATE TABLE IF NOT EXISTS `mature_access_profiles` (
  `userId` int NOT NULL,
  `fullName` varchar(255) NOT NULL,
  `email` varchar(320) NOT NULL,
  `phone` varchar(64) NOT NULL,
  `addressLine1` varchar(255) NOT NULL,
  `addressLine2` varchar(255) DEFAULT NULL,
  `city` varchar(128) NOT NULL,
  `stateRegion` varchar(128) NOT NULL,
  `postcode` varchar(32) NOT NULL,
  `country` varchar(128) NOT NULL,
  `dateOfBirth` date NOT NULL,
  `responsibilityAcceptedAt` datetime DEFAULT NULL,
  `consentPolicyAcceptedAt` datetime DEFAULT NULL,
  `phoneVerifiedAt` datetime DEFAULT NULL,
  `identityVerificationSessionId` varchar(255) DEFAULT NULL,
  `identityVerifiedAt` datetime DEFAULT NULL,
  `cardVerificationSessionId` varchar(255) DEFAULT NULL,
  `cardholderName` varchar(255) DEFAULT NULL,
  `cardNameMatchedAt` datetime DEFAULT NULL,
  `accessStatus` varchar(32) NOT NULL DEFAULT 'pending',
  `rejectionReason` text,
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`userId`),
  KEY `idx_mature_access_status` (`accessStatus`),
  KEY `idx_mature_access_phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
