import type { ToolIconKey } from "@/constants/hollywoodIcons";
import type { VirelleCinemaIconKey } from "@/constants/virelleCinemaIcons";

export const TOOL_TO_VIRELLE_CINEMA_ICON: Record<ToolIconKey, VirelleCinemaIconKey> = {
  ai_casting: "casting",
  asset_marketplace: "marketplace",
  budget_estimator: "reports",
  characters: "casting",
  color_grading: "editing",
  content_creator: "distribution",
  continuity_checker: "reports",
  credits: "billing",
  credits_editor: "editing",
  dialogue_enhancer: "sound",
  director_chat: "ai_tools",
  full_film_generator: "studio",
  location_scout: "scenes",
  mood_board: "storyboards",
  multi_shot_sequencer: "editing",
  nle_export: "distribution",
  poster_maker: "reports",
  referrals: "team",
  scene_builder: "scenes",
  script_writer: "scripts",
  settings: "dashboard",
  shot_list: "scenes",
  sound_effects: "sound",
  storyboard: "storyboards",
  subscription_plans: "billing",
  subtitles: "editing",
  team_collaboration: "team",
  trailer_studio: "editing",
  vfx_suite: "vfx",
  video_generation: "render",
  visual_effects: "vfx",
};

export const NAV_LABEL_TO_VIRELLE_CINEMA_ICON: Record<string, VirelleCinemaIconKey> = {
  Projects: "projects",
  "Director's AI": "ai_tools",
  Characters: "casting",
  "VFX & Sound": "vfx",
  "Swappys & Broadcast": "distribution",
  "Poster Maker": "reports",
  "Location Studio": "scenes",
  "Accessibility Studio": "editing",
  "Music Studio": "music",
  "Dubbing Studio": "sound",
  "Film Showcase": "distribution",
  Funding: "billing",
  Marketplace: "marketplace",
  Credits: "billing",
  Settings: "dashboard",
  "Signature Cast": "casting",
  "Project Samples": "studio",
  Campaigns: "distribution",
  Community: "team",
  "Admin & Seeding": "studio",
  "User Management": "team",
  Security: "support",
  "Growth Dashboard": "reports",
  "Autonomous Pipeline": "ai_tools",
  Advertising: "distribution",
  "SEO Dashboard": "reports",
  "Outreach & Email": "distribution",
};
