/**
 * VirÉlle Studios — Autonomous Content Creator Engine
 *
 * Generates cinematic advertising content (images + videos) and feeds them
 * directly into the Marketing Engine for distribution and the SEO Engine
 * for web optimisation.
 *
 * Pipeline:
 *   1. LLM generates a creative brief for the target platform
 *   2. Image Generator creates a cinematic still (poster / ad creative)
 *   3. Video Generator creates a short cinematic clip (optional, async)
 *   4. Caption + hashtags are written by LLM
 *   5. Content is saved to marketing_content table with status "approved"
 *   6. Marketing Engine picks it up and distributes to the platform
 *   7. SEO Engine is notified to update meta / OG tags
 */

import { getDb } from "./db";
import { invokeLLM } from "./_core/llm";
import { generateImage } from "./_core/imageGeneration";
import { generateVideoWithFallback } from "./_core/videoGeneration";
import { storagePut } from "./storage";
import { logger } from "./_core/logger";
import { marketingContent, marketingActivityLog, blogArticles } from "../drizzle/schema";
import { eq, desc, and } from "drizzle-orm";
import { sql } from "drizzle-orm";

const log = logger;

// ─── Platform definitions ─────────────────────────────────────────────────────

export type AdPlatform =
  | "instagram"
  | "tiktok"
  | "facebook"
  | "x_twitter"
  | "linkedin"
  | "youtube_shorts"
  | "pinterest";

export type ContentFormat = "image_post" | "video_reel" | "story" | "carousel" | "banner_ad";

export interface ContentBrief {
  platform: AdPlatform;
  format: ContentFormat;
  theme: string;           // e.g. "AI film production", "cinematic storytelling"
  hook: string;            // opening line / attention grabber
  caption: string;         // full post caption
  hashtags: string[];
  imagePrompt: string;     // detailed prompt for image generation
  videoPrompt: string;     // detailed prompt for video generation
  cta: string;             // call to action
  aspectRatio: "landscape" | "portrait";
}

export interface ContentCreatorResult {
  success: boolean;
  contentId?: number;
  imageUrl?: string;
  videoUrl?: string;
  caption?: string;
  hashtags?: string[];
  platform: AdPlatform;
  error?: string;
}

// ─── Platform-specific style guides ──────────────────────────────────────────

const PLATFORM_STYLES: Record<AdPlatform, {
  aspectRatio: "landscape" | "portrait";
  preferVideo: boolean;
  maxHashtags: number;
  tone: string;
  visualStyle: string;
}> = {
  instagram: {
    aspectRatio: "portrait",
    preferVideo: true,
    maxHashtags: 15,
    tone: "aspirational, cinematic, premium",
    visualStyle: "Cinematic portrait, golden hour lighting, anamorphic lens flares, film grain, shallow depth of field",
  },
  tiktok: {
    aspectRatio: "portrait",
    preferVideo: true,
    maxHashtags: 8,
    tone: "energetic, authentic, behind-the-scenes",
    visualStyle: "Dynamic vertical video, fast cuts, bold text overlays, trending aesthetic, raw cinematic energy",
  },
  facebook: {
    aspectRatio: "landscape",
    preferVideo: false,
    maxHashtags: 5,
    tone: "informative, community-driven, professional",
    visualStyle: "Wide cinematic shot, dramatic lighting, professional film set aesthetic",
  },
  x_twitter: {
    aspectRatio: "landscape",
    preferVideo: false,
    maxHashtags: 4,
    tone: "punchy, industry-insider, thought-leadership",
    visualStyle: "Bold graphic, high contrast, minimal text, cinematic still frame",
  },
  linkedin: {
    aspectRatio: "landscape",
    preferVideo: false,
    maxHashtags: 5,
    tone: "professional, innovative, industry-leading",
    visualStyle: "Clean professional aesthetic, cinematic production quality, corporate-creative fusion",
  },
  youtube_shorts: {
    aspectRatio: "portrait",
    preferVideo: true,
    maxHashtags: 6,
    tone: "educational, inspiring, showcase",
    visualStyle: "Vertical cinematic video, dramatic reveal, professional grade footage",
  },
  pinterest: {
    aspectRatio: "portrait",
    preferVideo: false,
    maxHashtags: 10,
    tone: "inspirational, visual storytelling, mood board",
    visualStyle: "Aesthetic mood board, cinematic colour grading, film photography style",
  },
};

// ─── Content themes for Virelle Studios ──────────────────────────────────────

const CONTENT_THEMES = [
  "AI-powered film production — create Hollywood-quality films from your laptop",
  "Cinematic storytelling made accessible to independent filmmakers",
  "From script to screen in minutes with AI-generated scenes",
  "Professional character design and voice acting powered by AI",
  "The future of indie filmmaking is here — no crew required",
  "Stunning cinematic visuals generated by artificial intelligence",
  "Your story deserves a cinematic treatment — VirÉlle Studios delivers",
  "AI film production platform for the next generation of storytellers",
  "Generate entire film scenes with a single prompt",
  "Professional-grade cinematography, democratised by AI",
];

// ─── Core: Generate content brief via LLM ────────────────────────────────────

export async function generateContentBrief(
  platform: AdPlatform,
  theme?: string
): Promise<ContentBrief | null> {
  const style = PLATFORM_STYLES[platform];
  const selectedTheme = theme || CONTENT_THEMES[Math.floor(Math.random() * CONTENT_THEMES.length)];

  try {
    const response = await invokeLLM({
      messages: [
        {
          role: "system",
          content: `You are a world-class advertising creative director specialising in AI technology and film production brands.
You create viral, high-converting advertising content for VirÉlle Studios — an AI-powered film production platform at virelle.life.

VirÉlle Studios allows filmmakers to:
- Generate cinematic scenes using AI (Sora/Runway ML)
- Create AI characters with voice acting
- Write and produce full scripts
- Export professional-quality films

Platform: ${platform}
Visual style: ${style.visualStyle}
Tone: ${style.tone}
Aspect ratio: ${style.aspectRatio}
Max hashtags: ${style.maxHashtags}

Create advertising content that is genuinely compelling, not generic. Focus on the emotional impact of democratising filmmaking.`,
        },
        {
          role: "user",
          content: `Create an advertising content brief for this theme: "${selectedTheme}"

Return JSON with these exact fields:
- platform: "${platform}"
- format: one of "image_post", "video_reel", "story", "carousel", "banner_ad"
- theme: the theme (string)
- hook: attention-grabbing opening line (max 12 words, punchy)
- caption: full post caption with line breaks (150-300 chars)
- hashtags: array of ${style.maxHashtags} relevant hashtags (no # prefix)
- imagePrompt: detailed Stable Diffusion / DALL-E prompt for a cinematic advertising image (100-200 words, very specific about lighting, composition, mood, style)
- videoPrompt: detailed prompt for a 4-8 second cinematic video clip (describe motion, camera movement, subject, lighting)
- cta: call to action text (max 8 words)
- aspectRatio: "${style.aspectRatio}"`,
        },
      ],
      response_format: {
        type: "json_schema",
        json_schema: {
          name: "content_brief",
          strict: true,
          schema: {
            type: "object",
            properties: {
              platform: { type: "string" },
              format: { type: "string" },
              theme: { type: "string" },
              hook: { type: "string" },
              caption: { type: "string" },
              hashtags: { type: "array", items: { type: "string" } },
              imagePrompt: { type: "string" },
              videoPrompt: { type: "string" },
              cta: { type: "string" },
              aspectRatio: { type: "string" },
            },
            required: ["platform", "format", "theme", "hook", "caption", "hashtags", "imagePrompt", "videoPrompt", "cta", "aspectRatio"],
            additionalProperties: false,
          },
        },
      },
    });

    const brief = JSON.parse((response.choices[0].message.content as string) || "{}");
    return brief as ContentBrief;
  } catch (err: unknown) {
    log.error("[ContentCreator] Failed to generate content brief:", { error: String(err) });
    return null;
  }
}

// ─── Core: Generate cinematic image ──────────────────────────────────────────

export async function generateAdImage(brief: ContentBrief): Promise<string | null> {
  try {
    // Enhance the prompt with Virelle Studios branding cues
    const enhancedPrompt = `${brief.imagePrompt}

Style requirements: Ultra-cinematic, professional advertising quality, ${brief.aspectRatio} composition.
Brand: VirÉlle Studios — AI film production platform. Sophisticated, premium, cutting-edge.
No text overlays in the image. Pure visual storytelling.`;

    const result = await generateImage({ prompt: enhancedPrompt });
    if (!result?.url) return null;

    // Download and upload to S3 for permanent storage
    const imageResponse = await fetch(result.url);
    const imageBuffer = Buffer.from(await imageResponse.arrayBuffer());
    const key = `content-creator/${brief.platform}/${Date.now()}-${Math.random().toString(36).slice(2, 8)}.png`;
    const { url: s3Url } = await storagePut(key, imageBuffer, "image/png");

    log.info(`[ContentCreator] Generated image for ${brief.platform}: ${s3Url}`);
    return s3Url;
  } catch (err: unknown) {
    log.error("[ContentCreator] Image generation failed:", { error: String(err) });
    return null;
  }
}

// ─── Core: Generate cinematic video clip ─────────────────────────────────────

export async function generateAdVideo(brief: ContentBrief, referenceImageUrl?: string): Promise<string | null> {
  try {
    const result = await generateVideoWithFallback({
      prompt: brief.videoPrompt,
      seconds: 6,
      resolution: "720p",
      aspectRatio: brief.aspectRatio,
      inputImageUrl: referenceImageUrl,
    });

    log.info(`[ContentCreator] Generated video for ${brief.platform}: ${result.videoUrl}`);
    return result.videoUrl;
  } catch (err: unknown) {
    log.error("[ContentCreator] Video generation failed:", { error: String(err) });
    return null;
  }
}

// ─── Core: Save content to database ──────────────────────────────────────────

export async function saveContentToDb(
  brief: ContentBrief,
  imageUrl: string | null,
  videoUrl: string | null
): Promise<number | null> {
  const db = await getDb();
  if (!db) return null;

  try {
    const caption = `${brief.hook}\n\n${brief.caption}\n\n${brief.cta}\n\n${brief.hashtags.map(h => `#${h}`).join(" ")}`;

    const result = await db.insert(marketingContent).values({
      platform: brief.platform,
      type: videoUrl ? "video_reel" : "image_post",
      headline: brief.hook,
      body: caption,
      imageUrl: imageUrl || undefined,
      videoUrl: videoUrl || undefined,
      status: "approved", // Ready for distribution
      metrics: {
        theme: brief.theme,
        hashtags: brief.hashtags,
        cta: brief.cta,
        format: brief.format,
        aspectRatio: brief.aspectRatio,
      } as any,
    } as any);

    const contentId = (result as any)[0]?.insertId;
    log.info(`[ContentCreator] Saved content #${contentId} for ${brief.platform}`);
    return contentId;
  } catch (err: unknown) {
    log.error("[ContentCreator] Failed to save content:", { error: String(err) });
    return null;
  }
}

// ─── Main: Run a single content creation job ─────────────────────────────────

export async function runContentCreatorJob(
  platform: AdPlatform,
  options: {
    theme?: string;
    generateVideo?: boolean;
    blogPostSlug?: string;
  } = {}
): Promise<ContentCreatorResult> {
  log.info(`[ContentCreator] Starting job for platform: ${platform}`);

  // 1. Get theme — optionally from a blog post
  let theme = options.theme;
  if (!theme && options.blogPostSlug) {
    const db = await getDb();
    if (db) {
      const posts = await db
        .select({ title: blogArticles.title, excerpt: blogArticles.excerpt })
        .from(blogArticles)
        .where(eq(blogArticles.slug, options.blogPostSlug))
        .limit(1);
      if (posts[0]) {
        theme = `${posts[0].title}: ${posts[0].excerpt || ""}`;
      }
    }
  }

  // 2. Generate creative brief
  const brief = await generateContentBrief(platform, theme);
  if (!brief) {
    return { success: false, platform, error: "Failed to generate content brief" };
  }

  // 3. Generate cinematic image
  const imageUrl = await generateAdImage(brief);

  // 4. Optionally generate video (uses image as first frame if available)
  let videoUrl: string | null = null;
  const style = PLATFORM_STYLES[platform];
  if (options.generateVideo !== false && style.preferVideo) {
    videoUrl = await generateAdVideo(brief, imageUrl || undefined);
  }

  // 5. Save to database
  const contentId = await saveContentToDb(brief, imageUrl, videoUrl);

  // 6. Log activity
  const db = await getDb();
  if (db && contentId) {
    await db.insert(marketingActivityLog).values({
      action: "content_created",
      description: `Content created for ${platform}: "${brief.hook}"`,
      metadata: {
        contentId,
        platform,
        theme: brief.theme,
        hasImage: !!imageUrl,
        hasVideo: !!videoUrl,
      } as any,
    } as any);
  }

  const caption = `${brief.hook}\n\n${brief.caption}\n\n${brief.cta}`;

  return {
    success: true,
    contentId: contentId || undefined,
    imageUrl: imageUrl || undefined,
    videoUrl: videoUrl || undefined,
    caption,
    hashtags: brief.hashtags,
    platform,
  };
}

// ─── Batch: Run content creation for multiple platforms ──────────────────────

export async function runContentCreatorBatch(
  platforms: AdPlatform[] = ["instagram", "tiktok", "facebook", "x_twitter"],
  options: { generateVideo?: boolean; theme?: string } = {}
): Promise<ContentCreatorResult[]> {
  log.info(`[ContentCreator] Running batch for platforms: ${platforms.join(", ")}`);
  const results: ContentCreatorResult[] = [];

  for (const platform of platforms) {
    try {
      const result = await runContentCreatorJob(platform, options);
      results.push(result);
      // Small delay between platforms to avoid rate limiting
      await new Promise(resolve => setTimeout(resolve, 2000));
    } catch (err: unknown) {
      log.error(`[ContentCreator] Batch job failed for ${platform}:`, { error: String(err) });
      results.push({ success: false, platform, error: String(err) });
    }
  }

  log.info(`[ContentCreator] Batch complete: ${results.filter(r => r.success).length}/${results.length} succeeded`);
  return results;
}

// ─── Stats: Get content creator statistics ───────────────────────────────────

export async function getContentCreatorStats(): Promise<{
  totalCreated: number;
  byPlatform: Record<string, number>;
  recentContent: Array<{
    id: number;
    platform: string;
    headline: string;
    status: string;
    hasVideo: boolean;
    createdAt: Date;
  }>;
}> {
  const db = await getDb();
  if (!db) {
    return { totalCreated: 0, byPlatform: {}, recentContent: [] };
  }

  const allContent = await db
    .select()
    .from(marketingContent)
    .orderBy(desc(marketingContent.createdAt))
    .limit(100);

  const byPlatform: Record<string, number> = {};
  for (const c of allContent) {
    byPlatform[c.platform] = (byPlatform[c.platform] || 0) + 1;
  }

  return {
    totalCreated: allContent.length,
    byPlatform,
    recentContent: allContent.slice(0, 20).map(c => ({
      id: c.id as number,
      platform: c.platform,
      headline: c.headline || "Untitled",
      status: c.status,
      hasVideo: !!(c as any).videoUrl,
      createdAt: c.createdAt,
    })),
  };
}
