/**
 * Funding Sources Seed Data
 * Pre-configured funding options for filmmakers
 */

export const FUNDING_SOURCES_DATA = [
  // Traditional Funding
  {
    id: "film-commission-grants",
    name: "Film Commission Grants",
    category: "Government",
    description: "State and local film commission grants for production",
    minAmount: 5000,
    maxAmount: 250000,
    interestRate: 0,
    term: 12,
    requirements: "Proof of production, budget breakdown, distribution plan",
    url: "https://www.filmcommission.org",
    active: true,
  },
  {
    id: "arts-council-funding",
    name: "Arts Council Funding",
    category: "Government",
    description: "Arts council grants for independent filmmakers",
    minAmount: 2000,
    maxAmount: 50000,
    interestRate: 0,
    term: 12,
    requirements: "Artist statement, project proposal, budget",
    url: "https://www.arts.gov",
    active: true,
  },
  {
    id: "nea-grants",
    name: "NEA (National Endowment for the Arts)",
    category: "Government",
    description: "Federal grants for arts projects including film",
    minAmount: 5000,
    maxAmount: 100000,
    interestRate: 0,
    term: 12,
    requirements: "Project narrative, budget, timeline",
    url: "https://www.nea.gov",
    active: true,
  },

  // Crowdfunding
  {
    id: "kickstarter-film",
    name: "Kickstarter",
    category: "Crowdfunding",
    description: "Reward-based crowdfunding platform for creative projects",
    minAmount: 100,
    maxAmount: 1000000,
    interestRate: 0,
    term: 6,
    requirements: "Video pitch, reward tiers, compelling story",
    url: "https://www.kickstarter.com",
    active: true,
  },
  {
    id: "indiegogo-film",
    name: "Indiegogo",
    category: "Crowdfunding",
    description: "Flexible crowdfunding for film and video projects",
    minAmount: 100,
    maxAmount: 500000,
    interestRate: 0,
    term: 6,
    requirements: "Campaign video, clear goals, updates",
    url: "https://www.indiegogo.com",
    active: true,
  },

  // Film Festivals & Competitions
  {
    id: "sundance-labs",
    name: "Sundance Labs",
    category: "Festival",
    description: "Sundance Institute fellowships and labs for filmmakers",
    minAmount: 5000,
    maxAmount: 50000,
    interestRate: 0,
    term: 12,
    requirements: "Application, script/concept, creative statement",
    url: "https://www.sundance.org",
    active: true,
  },
  {
    id: "tribeca-film-institute",
    name: "Tribeca Film Institute",
    category: "Festival",
    description: "Grants and support for independent filmmakers",
    minAmount: 3000,
    maxAmount: 75000,
    interestRate: 0,
    term: 12,
    requirements: "Project proposal, budget, timeline",
    url: "https://www.tribecafilm.org",
    active: true,
  },
  {
    id: "sxsw-grants",
    name: "SXSW Film Grants",
    category: "Festival",
    description: "Grants and sponsorships from SXSW for film projects",
    minAmount: 2000,
    maxAmount: 50000,
    interestRate: 0,
    term: 12,
    requirements: "Submission to SXSW, project proposal",
    url: "https://www.sxsw.com",
    active: true,
  },

  // Production Companies & Studios
  {
    id: "production-company-deals",
    name: "Production Company Deals",
    category: "Industry",
    description: "Financing from production companies and studios",
    minAmount: 50000,
    maxAmount: 5000000,
    interestRate: 5,
    term: 24,
    requirements: "Pitch deck, script, director/producer credentials",
    url: "https://www.producersguild.org",
    active: true,
  },
  {
    id: "talent-agency-financing",
    name: "Talent Agency Financing",
    category: "Industry",
    description: "Financing through talent agencies for projects with attached talent",
    minAmount: 100000,
    maxAmount: 10000000,
    interestRate: 6,
    term: 24,
    requirements: "Attached talent, script, budget breakdown",
    url: "https://www.sagaftra.org",
    active: true,
  },

  // Bank & Traditional Loans
  {
    id: "film-production-loan",
    name: "Film Production Loan",
    category: "Banking",
    description: "Traditional bank loans for film production",
    minAmount: 25000,
    maxAmount: 2000000,
    interestRate: 8,
    term: 36,
    requirements: "Business plan, collateral, credit check",
    url: "https://www.sba.gov",
    active: true,
  },
  {
    id: "equipment-financing",
    name: "Equipment Financing",
    category: "Banking",
    description: "Financing for cameras, lighting, and production equipment",
    minAmount: 5000,
    maxAmount: 500000,
    interestRate: 7,
    term: 36,
    requirements: "Equipment list, business plan",
    url: "https://www.sba.gov",
    active: true,
  },

  // Angel Investors & VC
  {
    id: "angel-investors",
    name: "Angel Investors",
    category: "Investment",
    description: "Individual investors interested in film projects",
    minAmount: 10000,
    maxAmount: 1000000,
    interestRate: 0,
    term: 24,
    requirements: "Pitch deck, financial projections, equity terms",
    url: "https://www.angellist.com",
    active: true,
  },
  {
    id: "venture-capital",
    name: "Venture Capital",
    category: "Investment",
    description: "VC funding for film tech and production startups",
    minAmount: 100000,
    maxAmount: 10000000,
    interestRate: 0,
    term: 36,
    requirements: "Business model, market analysis, team credentials",
    url: "https://www.crunchbase.com",
    active: true,
  },

  // Streaming Platforms
  {
    id: "netflix-production",
    name: "Netflix Production Deals",
    category: "Streaming",
    description: "Direct production deals and financing from Netflix",
    minAmount: 500000,
    maxAmount: 50000000,
    interestRate: 0,
    term: 24,
    requirements: "Pitch, director/producer track record, concept",
    url: "https://www.netflix.com/jobs",
    active: true,
  },
  {
    id: "amazon-studios",
    name: "Amazon Studios Financing",
    category: "Streaming",
    description: "Production financing from Amazon Studios",
    minAmount: 500000,
    maxAmount: 50000000,
    interestRate: 0,
    term: 24,
    requirements: "Project proposal, team credentials",
    url: "https://www.amazonstudios.com",
    active: true,
  },
  {
    id: "hulu-originals",
    name: "Hulu Originals Program",
    category: "Streaming",
    description: "Hulu original content financing",
    minAmount: 300000,
    maxAmount: 30000000,
    interestRate: 0,
    term: 24,
    requirements: "Concept, creative team, budget",
    url: "https://www.hulu.com",
    active: true,
  },
  {
    id: "apple-tv-plus",
    name: "Apple TV+ Originals",
    category: "Streaming",
    description: "Apple TV+ original content production deals",
    minAmount: 500000,
    maxAmount: 50000000,
    interestRate: 0,
    term: 24,
    requirements: "High-concept pitch, established creators",
    url: "https://www.apple.com/tv-plus",
    active: true,
  },

  // Grants & Scholarships
  {
    id: "film-school-grants",
    name: "Film School Grants",
    category: "Education",
    description: "Grants from film schools and universities",
    minAmount: 1000,
    maxAmount: 25000,
    interestRate: 0,
    term: 12,
    requirements: "Enrollment or alumni status, project proposal",
    url: "https://www.afci.org",
    active: true,
  },
  {
    id: "diversity-grants",
    name: "Diversity & Inclusion Grants",
    category: "Grants",
    description: "Grants supporting underrepresented filmmakers",
    minAmount: 2000,
    maxAmount: 100000,
    interestRate: 0,
    term: 12,
    requirements: "Proof of identity, project proposal, budget",
    url: "https://www.blackfilmmakers.org",
    active: true,
  },
  {
    id: "women-filmmakers-fund",
    name: "Women Filmmakers Fund",
    category: "Grants",
    description: "Grants specifically for women directors and producers",
    minAmount: 3000,
    maxAmount: 75000,
    interestRate: 0,
    term: 12,
    requirements: "Project proposal, budget, creative statement",
    url: "https://www.wif.org",
    active: true,
  },

  // International Funding - Americas
  {
    id: "colombia-film-rebate",
    name: "Colombia Film Fund (CFF)",
    category: "International",
    description: "Generous 40% cash rebate for film production and 20% for logistics in Colombia",
    minAmount: 50000,
    maxAmount: 2000000,
    interestRate: 0,
    term: 12,
    requirements: "Expenditure in Colombia, local production services",
    url: "https://www.locationcolombia.com",
    active: true,
  },
  {
    id: "mexico-imcine-grants",
    name: "IMCINE (Mexico)",
    category: "International",
    description: "Mexican Institute of Cinematography production and development grants",
    minAmount: 10000,
    maxAmount: 500000,
    interestRate: 0,
    term: 12,
    requirements: "Mexican co-production, cultural merit",
    url: "http://www.imcine.gob.mx",
    active: true,
  },
  {
    id: "california-film-tax-credit",
    name: "California Film & TV Tax Credit",
    category: "International",
    description: "20-25% tax credit for production in California",
    minAmount: 100000,
    maxAmount: 10000000,
    interestRate: 0,
    term: 12,
    requirements: "Minimum spend in California, job creation",
    url: "https://film.ca.gov",
    active: true,
  },

  // International Funding - Asia & India
  {
    id: "nfdc-india-production",
    name: "NFDC Production Fund (India)",
    category: "International",
    description: "National Film Development Corporation of India production and co-production funding",
    minAmount: 20000,
    maxAmount: 1000000,
    interestRate: 0,
    term: 24,
    requirements: "Indian co-production, script approval",
    url: "https://www.nfdcindia.com",
    active: true,
  },
  {
    id: "up-film-subsidy-india",
    name: "Uttar Pradesh Film Subsidy",
    category: "International",
    description: "Up to 25% subsidy for films shot in Uttar Pradesh, India",
    minAmount: 10000,
    maxAmount: 300000,
    interestRate: 0,
    term: 12,
    requirements: "Minimum 50% shooting in UP, local employment",
    url: "https://filmcityup.com",
    active: true,
  },
  {
    id: "kofic-location-incentive",
    name: "KOFIC Location Incentive (South Korea)",
    category: "International",
    description: "25% cash rebate on qualified production expenditures in South Korea",
    minAmount: 100000,
    maxAmount: 2000000,
    interestRate: 0,
    term: 12,
    requirements: "Minimum spend in Korea, local production services",
    url: "http://www.koreanfilm.or.kr",
    active: true,
  },
  {
    id: "asian-cinema-fund-acf",
    name: "Asian Cinema Fund (ACF)",
    category: "International",
    description: "Busan International Film Festival's fund for Asian independent films",
    minAmount: 10000,
    maxAmount: 50000,
    interestRate: 0,
    term: 12,
    requirements: "Asian director, project in development or post-production",
    url: "https://acf.biff.kr",
    active: true,
  },
  {
    id: "china-coproduction-incentive",
    name: "CFCC Co-Production Incentive (China)",
    category: "International",
    description: "Incentives for official co-productions with Chinese partners",
    minAmount: 500000,
    maxAmount: 5000000,
    interestRate: 0,
    term: 24,
    requirements: "Official co-production status, Chinese elements",
    url: "http://www.cfcc-film.com.cn",
    active: true,
  },
  {
    id: "japan-foundation-film-grants",
    name: "Japan Foundation Film Grants",
    category: "International",
    description: "Grants for projects promoting Japanese culture or co-productions",
    minAmount: 5000,
    maxAmount: 100000,
    interestRate: 0,
    term: 12,
    requirements: "Japanese connection, cultural exchange",
    url: "https://www.jpf.go.jp",
    active: true,
  },
  {
    id: "unijapan-coproduction-support",
    name: "UNIJAPAN Co-Production Support",
    category: "International",
    description: "Support for international co-productions involving Japanese partners",
    minAmount: 10000,
    maxAmount: 200000,
    interestRate: 0,
    term: 12,
    requirements: "Japanese co-producer, distribution plan",
    url: "http://www.unijapan.org",
    active: true,
  },

  // International Funding - Europe & UK
  {
    id: "british-film-institute",
    name: "British Film Institute",
    category: "International",
    description: "UK film funding and development support",
    minAmount: 5000,
    maxAmount: 500000,
    interestRate: 0,
    term: 12,
    requirements: "Project proposal, UK connection",
    url: "https://www.bfi.org.uk",
    active: true,
  },
  {
    id: "canadian-film-fund",
    name: "Canadian Film Fund",
    category: "International",
    description: "Canadian government film production funding",
    minAmount: 10000,
    maxAmount: 1000000,
    interestRate: 0,
    term: 12,
    requirements: "Canadian production, budget, timeline",
    url: "https://www.telefilm.ca",
    active: true,
  },
  {
    id: "european-film-fund",
    name: "European Film Fund",
    category: "International",
    description: "Pan-European co-production financing",
    minAmount: 25000,
    maxAmount: 2000000,
    interestRate: 0,
    term: 12,
    requirements: "Co-production agreement, budget",
    url: "https://www.eurimages.eu",
    active: true,
  },

  // Specialized Funding
  {
    id: "documentary-funding",
    name: "Documentary Funding Network",
    category: "Specialized",
    description: "Grants and financing for documentary projects",
    minAmount: 2000,
    maxAmount: 200000,
    interestRate: 0,
    term: 12,
    requirements: "Documentary proposal, research plan",
    url: "https://www.pbs.org",
    active: true,
  },
  {
    id: "animation-grants",
    name: "Animation Production Grants",
    category: "Specialized",
    description: "Grants for animated film and series production",
    minAmount: 5000,
    maxAmount: 500000,
    interestRate: 0,
    term: 12,
    requirements: "Animation samples, project proposal",
    url: "https://www.asifa.org",
    active: true,
  },
  {
    id: "short-film-grants",
    name: "Short Film Grants",
    category: "Specialized",
    description: "Grants specifically for short film production",
    minAmount: 500,
    maxAmount: 50000,
    interestRate: 0,
    term: 6,
    requirements: "Script/concept, budget under $50k",
    url: "https://www.shortfilmfund.org",
    active: true,
  },
];
