import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Shield } from "lucide-react";

export default function TermsOfService() {
  const [, setLocation] = useLocation();
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <Button variant="ghost" size="sm" onClick={() => setLocation("/")} className="mb-8 gap-2">
          <ArrowLeft className="h-4 w-4" /> Back to Home
        </Button>
        <div className="flex items-center gap-3 mb-2">
          <Shield className="h-6 w-6 text-primary" />
          <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
        </div>
        <p className="text-muted-foreground text-sm mb-10">Last updated: March 2026 · Effective immediately</p>

        <div className="prose prose-invert max-w-none space-y-8 text-sm leading-relaxed">

          <section>
            <h2 className="text-lg font-semibold mb-3 text-foreground">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground">
              By accessing or using Virelle Studios ("the Platform", "we", "us", or "our") at virelle.life or any associated services, you ("User", "Director", "you") agree to be bound by these Terms of Service ("Terms"). If you do not agree to all of these Terms, you must not access or use the Platform. These Terms constitute a legally binding agreement between you and Virelle Studios Ltd.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-foreground">2. Description of Service</h2>
            <p className="text-muted-foreground">
              Virelle Studios is an AI-powered film production platform that enables users to generate cinematic content including images, video scenes, scripts, voice acting, and soundtracks using artificial intelligence. The Platform acts as an orchestration layer connecting user inputs to third-party AI generation services.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-foreground">3. User Responsibilities and Content Liability</h2>
            <p className="text-muted-foreground mb-3">
              <strong className="text-foreground">You are solely and entirely responsible</strong> for all content you create, upload, input, or generate using the Platform. Virelle Studios provides tools; you direct their use. This includes but is not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>All scripts, story concepts, character descriptions, and creative inputs you provide</li>
              <li>All AI-generated content produced as a result of your inputs and instructions</li>
              <li>Any downstream use, distribution, publication, or monetisation of generated content</li>
              <li>Ensuring all content complies with applicable laws in your jurisdiction</li>
            </ul>
            <p className="text-muted-foreground mt-3">
              Virelle Studios is not liable for any content generated by users, including content that may infringe third-party rights, violate laws, or cause harm to any person or entity.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-foreground">4. Face, Likeness, and Biometric Data</h2>
            <div className="bg-amber-500/5 border border-amber-500/20 rounded-lg p-4 mb-4">
              <p className="text-amber-300 text-xs font-semibold uppercase tracking-wider mb-2">Important Legal Notice</p>
              <p className="text-muted-foreground">
                The use of any real person's face, likeness, voice, or biometric data without their explicit written consent may constitute a violation of privacy laws, personality rights, right of publicity statutes, and data protection regulations in many jurisdictions.
              </p>
            </div>
            <p className="text-muted-foreground mb-3">By uploading any photograph or reference image of a real person, you represent and warrant that:</p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li><strong className="text-foreground">Living persons:</strong> You have obtained explicit, informed, written consent from the individual whose likeness you are using, and that consent covers the specific use you intend on this Platform.</li>
              <li><strong className="text-foreground">Recently deceased persons (within 70 years of death):</strong> You have obtained written permission from the legal next of kin, estate, or authorised representative of the deceased.</li>
              <li><strong className="text-foreground">Historical public figures (deceased more than 70 years ago):</strong> You may use publicly available images of historical public figures provided the source image is of sufficient quality and the use does not defame, misrepresent, or create false impressions about the individual.</li>
              <li>You indemnify Virelle Studios against any and all claims arising from your use of any person's likeness on the Platform.</li>
            </ul>
            <p className="text-muted-foreground mt-3">
              Virelle Studios bears no responsibility whatsoever for any copyright infringement, right of publicity violation, defamation, or privacy breach arising from a user's use of real persons' likenesses. All such liability rests entirely with the user.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-foreground">5. Prohibited Content — Zero Tolerance</h2>
            <div className="bg-red-500/5 border border-red-500/20 rounded-lg p-4 mb-4">
              <p className="text-red-400 text-xs font-semibold uppercase tracking-wider mb-2">Zero Tolerance Policy</p>
              <p className="text-muted-foreground">
                The following categories of content are absolutely prohibited on the Platform. Violations will result in immediate permanent account termination, IP ban, and mandatory reporting to relevant law enforcement authorities.
              </p>
            </div>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li><strong className="text-foreground">Child Sexual Abuse Material (CSAM):</strong> Any generation, attempt to generate, or facilitation of sexually explicit content involving minors (persons under 18 years of age) is strictly prohibited. Any such attempt will result in immediate permanent account termination, IP ban, and mandatory reporting to the National Center for Missing &amp; Exploited Children (NCMEC), law enforcement agencies, and relevant child protection authorities in your jurisdiction. This applies to both real and AI-generated depictions of minors.</li>
              <li><strong className="text-foreground">Non-consensual intimate imagery:</strong> Generating sexually explicit content depicting real, identifiable individuals without their explicit consent.</li>
              <li><strong className="text-foreground">Defamatory content:</strong> Content designed to defame, harass, or harm specific individuals.</li>
              <li><strong className="text-foreground">Incitement to violence or terrorism:</strong> Content that promotes, glorifies, or incites violence, terrorism, or hate crimes.</li>
              <li><strong className="text-foreground">Illegal content:</strong> Any content that violates applicable laws in your jurisdiction or the jurisdiction of Virelle Studios.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-foreground">6. Content Moderation and Account Suspension</h2>
            <p className="text-muted-foreground mb-3">
              Virelle Studios operates an automated content moderation system that scans all inputs and generated content for potential policy violations. When a potential violation is detected:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>The user's account will be <strong className="text-foreground">immediately frozen</strong>, preventing further access to the Platform.</li>
              <li>An alert will be sent to the Virelle Studios safety team for review.</li>
              <li>The user will receive an email notification explaining that their account has been frozen pending review.</li>
              <li>The user may respond to the notification email to provide clarification.</li>
              <li>Virelle Studios will review the incident and, at its sole discretion, reinstate or permanently terminate the account.</li>
              <li>For CSAM violations, accounts will be permanently terminated without possibility of reinstatement, and the matter will be reported to law enforcement.</li>
            </ul>
            <p className="text-muted-foreground mt-3">
              Virelle Studios reserves the right to suspend or terminate any account at any time, for any reason, without prior notice, at its sole discretion.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-foreground">7. Copyright and Intellectual Property</h2>
            <p className="text-muted-foreground mb-3">
              You are solely responsible for ensuring that all content you input into the Platform does not infringe any third-party intellectual property rights, including copyrights, trademarks, patents, or trade secrets. Virelle Studios is not liable for any copyright infringement committed by users.
            </p>
            <p className="text-muted-foreground">
              Subject to your subscription plan, you retain ownership of the creative output generated through your use of the Platform, subject to the underlying rights of any third-party AI providers. Virelle Studios grants you a non-exclusive licence to use generated content for your stated purposes, subject to these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-foreground">8. Limitation of Liability</h2>
            <div className="bg-card/50 border border-border/50 rounded-lg p-4">
              <p className="text-muted-foreground">
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, VIRELLE STUDIOS, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND LICENSORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR USE OF OR INABILITY TO USE THE PLATFORM, ANY CONTENT GENERATED THROUGH THE PLATFORM, OR ANY THIRD-PARTY CLAIMS ARISING FROM YOUR USE OF THE PLATFORM.
              </p>
              <p className="text-muted-foreground mt-3">
                VIRELLE STUDIOS IS NOT LIABLE FOR ANY MISUSE OF THE PLATFORM BY USERS, INCLUDING BUT NOT LIMITED TO COPYRIGHT INFRINGEMENT, PRIVACY VIOLATIONS, DEFAMATION, OR ANY OTHER HARM CAUSED BY USER-GENERATED CONTENT.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-foreground">9. Indemnification</h2>
            <p className="text-muted-foreground">
              You agree to defend, indemnify, and hold harmless Virelle Studios and its officers, directors, employees, and agents from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable legal fees) arising out of or relating to your violation of these Terms, your use of the Platform, your content, or your violation of any third-party rights.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-foreground">10. Governing Law</h2>
            <p className="text-muted-foreground">
              These Terms shall be governed by and construed in accordance with applicable law. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the competent courts.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-foreground">11. Changes to Terms</h2>
            <p className="text-muted-foreground">
              Virelle Studios reserves the right to modify these Terms at any time. Continued use of the Platform after changes constitutes acceptance of the new Terms. We will notify users of material changes via email or platform notification.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-foreground">13. Error Reporting and Technical Support</h2>
            <p className="text-muted-foreground mb-3">
              In the event that you experience a technical error, generation failure, or any other malfunction on the Platform, you are required to report the issue by submitting a clear, descriptive email to{" "}
              <a href="mailto:studiosvirelle@gmail.com" className="text-primary hover:underline">studiosvirelle@gmail.com</a>. Your error report <strong className="text-foreground">must include one or more clear screenshots</strong> that accurately document the issue you have encountered. Reports submitted without supporting screenshots may not be actioned.
            </p>
            <p className="text-muted-foreground mb-3">
              Virelle Studios will endeavour to investigate and resolve reported errors within <strong className="text-foreground">24 hours</strong> of receiving a complete and valid error report. This 24-hour resolution window is a target and not a guarantee. Complex technical issues may require additional time to investigate and resolve. Virelle Studios accepts no liability for any loss, delay, or inconvenience caused by technical errors or the time taken to resolve them.
            </p>
            <p className="text-muted-foreground">
              Users acknowledge that the Platform is provided on an "as is" and "as available" basis, and that temporary errors, interruptions, or degraded performance may occur from time to time. Virelle Studios does not warrant that the Platform will be error-free or uninterrupted.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-foreground">14. Credits, Compensation, and Refunds</h2>
            <div className="bg-card/50 border border-border/50 rounded-lg p-4 mb-3">
              <p className="text-muted-foreground font-medium">
                <strong className="text-foreground">No credits, compensation, or refunds of any kind will be issued without express written approval from a Virelle Studios administrator.</strong>
              </p>
            </div>
            <p className="text-muted-foreground mb-3">
              Any request for a credit, generation credit top-up, monetary compensation, or subscription refund arising from a technical error, generation failure, or service interruption must be submitted via email to{" "}
              <a href="mailto:studiosvirelle@gmail.com" className="text-primary hover:underline">studiosvirelle@gmail.com</a>, accompanied by clear screenshots evidencing the issue. All such requests are subject to administrator review and approval, which may take <strong className="text-foreground">up to 24 hours</strong>.
            </p>
            <p className="text-muted-foreground mb-3">
              Virelle Studios reserves the sole and absolute right to approve or decline any request for compensation, credits, or refunds. Approval of one request does not constitute a precedent or obligation to approve future requests. Users have no automatic entitlement to any form of compensation or credit as a result of any error, interruption, or failure of the Platform.
            </p>
            <p className="text-muted-foreground">
              Any credits issued by Virelle Studios are non-transferable, have no monetary value, cannot be exchanged for cash, and expire upon account termination or as otherwise specified at the time of issuance. Credits issued as a goodwill gesture do not constitute an admission of fault or liability by Virelle Studios.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3 text-foreground">12. Contact</h2>
            <p className="text-muted-foreground">
              For legal inquiries, content moderation appeals, or questions about these Terms, contact us at: <a href="mailto:legal@virelle.life" className="text-primary hover:underline">legal@virelle.life</a>. For technical support and error reporting, contact us at: <a href="mailto:studiosvirelle@gmail.com" className="text-primary hover:underline">studiosvirelle@gmail.com</a>
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
