export const SWAPPYS_HTML = String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover" />
<title>Swappys</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#07070e;color:#f8fbff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}.app{max-width:520px;margin:auto;padding:16px 14px 44px}.hdr{display:flex;align-items:center;gap:12px;margin-bottom:14px}.logo{width:50px;height:50px;border-radius:15px;background:linear-gradient(135deg,#2510ff,#bc18ff 42%,#ff2e78 72%,#ffb000);display:grid;place-items:center;font-size:25px;font-weight:900}.hdr h1{margin:0;font-size:24px}.hdr p{margin:2px 0 0;color:#9ba8c7;font-size:11px}.panel{background:#ffffff0b;border:1px solid #ffffff18;border-radius:18px;padding:12px;margin-top:12px}.notice{font-size:11px;color:#f2d28b;line-height:1.45;border-color:#ffbf3f55;background:#ffbf3f0c}.camera{position:relative;aspect-ratio:3/4;background:#111325;border-radius:16px;overflow:hidden;display:grid;place-items:center}.camera video,.camera img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.placeholder{text-align:center;color:#8f9abb;font-size:12px;padding:20px}.watermark{position:absolute;right:8px;bottom:8px;background:#000a;border:1px solid #fff3;border-radius:8px;padding:5px 8px;font-size:9px;font-weight:800;letter-spacing:.5px;z-index:5}.controls{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.btn{border:0;border-radius:13px;padding:12px 8px;background:#20263b;color:#fff;font-weight:800;font-size:12px}.btn.primary{background:linear-gradient(135deg,#ff2e78,#922cff)}.btn.gold{background:linear-gradient(135deg,#ffbf3f,#ff8b2e);color:#171000}.btn.danger{background:#5b1720}.btn:disabled{opacity:.38}.uploads{display:grid;grid-template-columns:1fr 1fr;gap:10px}.upload{position:relative;aspect-ratio:1;border:2px dashed #ffffff25;border-radius:16px;display:grid;place-items:center;text-align:center;overflow:hidden;background:#0c0d19}.upload input{position:absolute;inset:0;opacity:0;width:100%;height:100%}.upload img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.upload span{z-index:2;font-size:11px;color:#aeb8d1;padding:8px}.consent{display:flex;gap:9px;align-items:flex-start;font-size:11px;line-height:1.45;color:#c8d0e3}.consent input{width:20px;height:20px;accent-color:#ff2e78;flex:0 0 auto}.status{text-align:center;color:#9ba8c7;font-size:12px;min-height:18px;margin-top:10px}.status.ok{color:#4ade80}.status.err{color:#f87171}.result{display:none;position:relative;margin-top:12px}.result.show{display:block}.result img{display:block;width:100%;border-radius:16px}.upgrade{display:none}.upgrade.show{display:block}.small{font-size:10px;color:#8f9abb;line-height:1.4;margin-top:7px}
</style>
</head>
<body><div class="app">
<div class="hdr"><div class="logo">S</div><div><h1>Swappys</h1><p>AI face & body transformation · Virelle Studios</p></div></div>
<div class="panel notice">Use only media you own or have explicit permission to transform. Swappys marks preview outputs and does not permit deceptive, abusive, sexual, or non-consensual use.</div>
<div class="panel">
<div class="camera" id="cameraStage"><video id="cameraVideo" autoplay playsinline muted></video><img id="playback" hidden alt="Playback preview"/><div class="placeholder" id="cameraPlaceholder">Start the camera for live preview, or upload two photos below.</div><div class="watermark">SWAPPYS · AI ALTERED</div></div>
<div class="controls"><button class="btn primary" id="cameraBtn" onclick="toggleCamera()">Start camera</button><button class="btn" id="recordBtn" onclick="toggleRecord()" disabled>Record</button><button class="btn danger" onclick="resetCamera()">Delete</button></div>
<div class="small" id="recordInfo">Camera preview and recording remain on this device unless you intentionally submit media.</div>
</div>
<div class="panel uploads">
<label class="upload"><input id="sourceInput" type="file" accept="image/jpeg,image/png,image/webp" onchange="loadImage('source',this)"/><img id="sourcePreview" hidden/><span id="sourceText">Choose your source image</span></label>
<label class="upload"><input id="targetInput" type="file" accept="image/jpeg,image/png,image/webp" onchange="loadImage('target',this)"/><img id="targetPreview" hidden/><span id="targetText">Choose the target body/image</span></label>
</div>
<div class="panel consent"><input id="consent" type="checkbox" onchange="updateSwapButton()"/><label for="consent">I confirm that I own these images or have clear permission from every identifiable person, and that the result will not be used to impersonate, defraud, harass, exploit, or mislead anyone.</label></div>
<button class="btn primary" style="width:100%;padding:15px;font-size:15px" id="swapBtn" onclick="doSwap()" disabled>Swap face & body</button>
<div class="status" id="status">Connecting to Virelle AI…</div>
<div class="result" id="result"><img id="resultImage" alt="AI transformation result"/><div class="watermark" id="resultWatermark">SWAPPYS PREVIEW · virelle.life</div><div class="controls"><button class="btn gold" onclick="saveResult()">Save</button><button class="btn" onclick="doSwap()">Try again</button><button class="btn danger" onclick="clearResult()">Delete</button></div></div>
<div class="panel upgrade" id="upgrade"><strong>Unlock clean studio exports</strong><p class="small">Creator members receive higher-quality output and expanded Virelle production tools. Provenance records remain retained.</p><button class="btn gold" style="width:100%;margin-top:9px" onclick="joinCreator()">View Creator access</button></div>
</div>
<script>
let sourceData=null,targetData=null,stream=null,recorder=null,chunks=[],recordingUrl=null,virelleBaseUrl='https://virelle.life',virelleOk=false,busy=false;
const MAX_BYTES=10*1024*1024;
function post(payload){if(window.ReactNativeWebView)window.ReactNativeWebView.postMessage(JSON.stringify(payload));}
window.SwappysNative={setVirelleConnection(payload){virelleOk=Boolean(payload&&payload.ok);if(payload&&payload.baseUrl)virelleBaseUrl=payload.baseUrl;setStatus(payload.health||(virelleOk?'Virelle AI online':'Virelle AI unavailable'),virelleOk?'ok':'err');updateSwapButton();}};
function setStatus(message,type=''){const el=document.getElementById('status');el.textContent=message;el.className='status'+(type?' '+type:'');}
function updateSwapButton(){document.getElementById('swapBtn').disabled=busy||!sourceData||!targetData||!document.getElementById('consent').checked||!virelleOk;}
function validateImage(file){if(!file)return 'No image selected.';if(!['image/jpeg','image/png','image/webp'].includes(file.type))return 'Use a JPEG, PNG, or WebP image.';if(file.size>MAX_BYTES)return 'Each image must be under 10 MB.';return null;}
function loadImage(which,input){const file=input.files&&input.files[0];const error=validateImage(file);if(error){input.value='';setStatus(error,'err');return;}const reader=new FileReader();reader.onerror=()=>setStatus('Could not read that image.','err');reader.onload=()=>{const value=String(reader.result||'');if(which==='source'){sourceData=value;showPreview('source',value);}else{targetData=value;showPreview('target',value);}clearResult();setStatus('Images ready. Confirm consent to continue.');updateSwapButton();};reader.readAsDataURL(file);}
function showPreview(which,value){const img=document.getElementById(which+'Preview');img.src=value;img.hidden=false;document.getElementById(which+'Text').hidden=true;}
async function toggleCamera(){if(stream){resetCamera();return;}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:true});const video=document.getElementById('cameraVideo');video.srcObject=stream;document.getElementById('cameraPlaceholder').hidden=true;document.getElementById('cameraBtn').textContent='Stop camera';document.getElementById('recordBtn').disabled=false;setStatus('Camera ready.');}catch(error){setStatus(error&&error.name==='NotAllowedError'?'Camera permission was denied. Enable it in device settings.':'Camera could not start on this device.','err');}}
function supportedMime(){const types=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm','video/mp4'];return types.find(t=>window.MediaRecorder&&MediaRecorder.isTypeSupported(t))||'';}
function toggleRecord(){if(!stream)return;if(recorder&&recorder.state==='recording'){recorder.stop();return;}try{chunks=[];const mime=supportedMime();recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);recorder.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data);};recorder.onstop=()=>{const blob=new Blob(chunks,{type:recorder.mimeType||'video/webm'});if(recordingUrl)URL.revokeObjectURL(recordingUrl);recordingUrl=URL.createObjectURL(blob);const playback=document.getElementById('playback');playback.hidden=true;document.getElementById('recordInfo').textContent='Recording captured locally. Use Delete to discard it.';document.getElementById('recordBtn').textContent='Record';};recorder.start(500);document.getElementById('recordBtn').textContent='Stop';document.getElementById('recordInfo').textContent='Recording…';}catch{setStatus('Recording is not supported by this browser build.','err');}}
function resetCamera(){if(recorder&&recorder.state==='recording')recorder.stop();if(stream)stream.getTracks().forEach(track=>track.stop());stream=null;document.getElementById('cameraVideo').srcObject=null;document.getElementById('cameraPlaceholder').hidden=false;document.getElementById('cameraBtn').textContent='Start camera';document.getElementById('recordBtn').disabled=true;document.getElementById('recordBtn').textContent='Record';if(recordingUrl){URL.revokeObjectURL(recordingUrl);recordingUrl=null;}document.getElementById('recordInfo').textContent='Camera preview and recording remain on this device unless you intentionally submit media.';}
async function doSwap(){if(busy||!sourceData||!targetData||!document.getElementById('consent').checked)return;busy=true;updateSwapButton();clearResult();setStatus('Creating transformation…');try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),90000);const response=await fetch(virelleBaseUrl+'/api/trpc/vfxSfx.swappysMobileSwap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({json:{sourceImageBase64:sourceData,targetImageBase64:targetData,consentConfirmed:true}}),credentials:'include',signal:controller.signal});clearTimeout(timer);let data=null;try{data=await response.json();}catch{}if(!response.ok)throw new Error(data?.error?.json?.message||data?.error?.message||'Server rejected the transformation.');const result=data?.result?.data?.json??data?.result?.data;if(!result?.imageUrl)throw new Error('No output image was returned.');document.getElementById('resultImage').src=result.imageUrl;document.getElementById('result').classList.add('show');document.getElementById('resultWatermark').style.display=result.hasWatermark===false?'none':'block';document.getElementById('upgrade').classList.toggle('show',result.hasWatermark!==false);setStatus('Transformation complete.','ok');}catch(error){setStatus(error&&error.name==='AbortError'?'The request timed out. Try smaller or clearer images.':(error.message||'Transformation failed.'),'err');}finally{busy=false;updateSwapButton();}}
function clearResult(){document.getElementById('result').classList.remove('show');document.getElementById('resultImage').removeAttribute('src');document.getElementById('upgrade').classList.remove('show');}
function saveResult(){const url=document.getElementById('resultImage').src;if(url)post({type:'saveResult',url});}
function joinCreator(){post({type:'openUrl',url:virelleBaseUrl+'/register?source=swappys-mobile&product=swappys&intent=creator-upgrade'});}
window.addEventListener('beforeunload',resetCamera);post({type:'appReady'});
</script></body></html>`;
