#!/usr/bin/env tsx
/**
 * sync-mobile-constants.ts
 *
 * Extracts the canonical tier/pricing/credits constants from the web server's
 * subscription.ts and writes a generated TypeScript file into the mobile repo.
 *
 * Run manually:  pnpm sync-mobile
 * Run in CI:     automatically triggered by the "sync-mobile-constants" workflow
 *
 * The generated file is committed to virellestudios-mobile and should NEVER
 * be edited by hand — edit subscription.ts in this repo instead.
 */

import {
  TIER_LIMITS,
  TIER_PRICING,
  TIER_DISPLAY_NAMES,
  TOP_UP_PACKS,
  CREDIT_COSTS,
  REFERRAL_REWARDS,
  LAUNCH_SPECIAL_ACTIVE,
  LAUNCH_SPECIAL_DISCOUNT,
} from "../server/_core/subscription.js";
import type { SubscriptionTier } from "../server/_core/subscription.js";
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// ─── Tier ordering for display ────────────────────────────────────────────────
const TIER_ORDER: SubscriptionTier[] = [
  "indie",
  "amateur",
  "independent",
  "creator",
  "studio",
  "industry",
  "beta",
];

// ─── Build monthly credits map (used in mobile routers.ts) ───────────────────
const tierCreditsMap: Record<string, number> = {};
for (const tier of TIER_ORDER) {
  if (TIER_LIMITS[tier]) {
    tierCreditsMap[tier] = TIER_LIMITS[tier].monthlyCredits;
  }
}
// Ensure legacy "free" tier is present
tierCreditsMap["free"] = 0;

// ─── Build self-serve tiers list ─────────────────────────────────────────────
const selfServeTiers = TIER_ORDER.filter(
  (t) => t !== "studio" && t !== "industry" && t !== "beta"
);

// ─── Generate file content ────────────────────────────────────────────────────
const banner = `/**
 * ⚠️  AUTO-GENERATED — DO NOT EDIT BY HAND
 *
 * Generated by: virellestudios/scripts/sync-mobile-constants.ts
 * Source of truth: virellestudios/server/_core/subscription.ts
 *
 * To update: run \`pnpm sync-mobile\` in the virellestudios repo,
 * then commit the result in virellestudios-mobile.
 *
 * Last generated: ${new Date().toISOString()}
 */
`;

const content = `${banner}
export type SubscriptionTier = ${TIER_ORDER.map((t) => `"${t}"`).join(" | ")};

export const TIER_DISPLAY_NAMES: Record<string, string> = ${JSON.stringify(TIER_DISPLAY_NAMES, null, 2)};

export const TIER_ORDER: SubscriptionTier[] = ${JSON.stringify(TIER_ORDER, null, 2)};

export const SELF_SERVE_TIERS: SubscriptionTier[] = ${JSON.stringify(selfServeTiers, null, 2)};

/** Monthly credits granted per subscription tier */
export const TIER_MONTHLY_CREDITS: Record<string, number> = ${JSON.stringify(tierCreditsMap, null, 2)};

/** Pricing in AUD cents */
export const TIER_PRICING = ${JSON.stringify(TIER_PRICING, null, 2)} as const;

/** Feature flags per tier */
export const TIER_LIMITS = ${JSON.stringify(TIER_LIMITS, null, 2)} as const;

/** Credit costs per action */
export const CREDIT_COSTS = ${JSON.stringify(CREDIT_COSTS, null, 2)} as const;

/** One-time top-up packs */
export const TOP_UP_PACKS = ${JSON.stringify(TOP_UP_PACKS, null, 2)} as const;

/** Referral reward config */
export const REFERRAL_REWARDS = ${JSON.stringify(REFERRAL_REWARDS, null, 2)} as const;

export const LAUNCH_SPECIAL_ACTIVE = ${LAUNCH_SPECIAL_ACTIVE};
export const LAUNCH_SPECIAL_DISCOUNT = ${LAUNCH_SPECIAL_DISCOUNT};

/**
 * Returns true if a user's tier can access a given feature.
 * Mirrors isSelfServeTier() and TIER_LIMITS checks from the web server.
 */
export function tierHasFeature(
  userTier: string,
  feature: keyof typeof TIER_LIMITS["indie"]
): boolean {
  const limits = TIER_LIMITS[userTier as SubscriptionTier];
  if (!limits) return false;
  const val = limits[feature];
  return val !== false && val !== 0;
}

/**
 * Returns true if userTier meets or exceeds the required minTier.
 */
export function tierMeetsMinimum(
  userTier: string,
  minTier: SubscriptionTier
): boolean {
  const userIdx = TIER_ORDER.indexOf(userTier as SubscriptionTier);
  const minIdx = TIER_ORDER.indexOf(minTier);
  if (userIdx === -1 || minIdx === -1) return false;
  return userIdx >= minIdx;
}
`;

// ─── Write to mobile repo ─────────────────────────────────────────────────────
const MOBILE_REPO = resolve(__dirname, "../../virellestudios-mobile");
const outPath = resolve(MOBILE_REPO, "shared/_core/subscription-constants.ts");

writeFileSync(outPath, content, "utf-8");
console.log(`✅  Written: ${outPath}`);
console.log(`   Tiers: ${TIER_ORDER.join(", ")}`);
console.log(`   Self-serve: ${selfServeTiers.join(", ")}`);
console.log(`   Credit costs: ${Object.keys(CREDIT_COSTS).length} actions`);
console.log(`   Top-up packs: ${TOP_UP_PACKS.length}`);
